version: '3'


services:
  mysql:
    image: mysql
    container_name: mysql-local
    ports:
      - "3306:3306" # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: "local"
      MYSQL_DATABASE: "akgimi"
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis-local
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/var/lib/redis
      - ./redis/config:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf
volumes:
  mysql: