spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:~/testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  port: 8080
  servlet:
    context-path: /